name: Python automation framework CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-python-automation-framework-image:
    name: Build python automation framework docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3

      #Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #Build and push framework docker image
      - name: Build and push the python automation framework Docker image
        run: |
              docker build . --tag ghcr.io/modera70/python-infinity-growth:latest
              docker push ghcr.io/modera70/python-infinity-growth:latest